#!/usr/bin/env node
/**
 * embed-assets.mjs
 * Reads your exported + INT8-quantized model and bakes it into
 * src/assets.generated.ts as base64, along with the label order and
 * preprocessing parameters emitted by scripts/export_model.py.
 *
 * Usage:
 *   node scripts/embed-assets.mjs [model.onnx] [labels.json] [preprocess.json]
 *
 * Defaults (produced by export_model.py):
 *   model/nsfw.int8.onnx
 *   model/labels.json
 *   model/preprocess.json
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");

const modelPath = resolve(root, process.argv[2] || "model/nsfw.int8.onnx");
const labelsPath = resolve(root, process.argv[3] || "model/labels.json");
const preprocessPath = resolve(root, process.argv[4] || "model/preprocess.json");
const outPath = resolve(root, "src/assets.generated.ts");

if (!existsSync(modelPath)) {
  console.error(`[embed] model not found: ${modelPath}`);
  console.error("[embed] run scripts/export_model.py first (see README).");
  process.exit(1);
}

const modelB64 = readFileSync(modelPath).toString("base64");

const labels = existsSync(labelsPath) ? JSON.parse(readFileSync(labelsPath, "utf8")) : [];
const preprocess = existsSync(preprocessPath)
  ? JSON.parse(readFileSync(preprocessPath, "utf8"))
  : {};

if (!labels.length) {
  console.warn("[embed] WARNING: no labels.json — gating will use the (wrong) fallback order.");
}
if (!Object.keys(preprocess).length) {
  console.warn("[embed] WARNING: no preprocess.json — using EfficientNet defaults (verify accuracy).");
}

const sizeMB = (Buffer.byteLength(modelB64, "utf8") / (1024 * 1024)).toFixed(2);

const file = `/**
 * AUTO-GENERATED by scripts/embed-assets.mjs — do not edit by hand.
 * Source model: ${process.argv[2] || "model/nsfw.int8.onnx"} (${sizeMB} MB base64)
 */
export const MODEL_B64 = ${JSON.stringify(modelB64)};
export const LABELS: string[] = ${JSON.stringify(labels)};
export const PREPROCESS: Record<string, unknown> = ${JSON.stringify(preprocess)};
export const EMBEDDED = true;
`;

writeFileSync(outPath, file);
console.log(`[embed] wrote ${outPath}`);
console.log(`[embed] model: ${sizeMB} MB base64 | labels: ${JSON.stringify(labels)}`);
